SELECT * FROM PRODUTOS

UPDATE [PRODUTOS] SET [PREÇO LISTA] = 5
WHERE [CÓDIGO] = '1040107'

UPDATE [PRODUTOS] SET [SABOR] = 'Laranja', [EMBALAGEM] = 'PET'
WHERE [CÓDIGO] = '1040107'

SELECT * FROM PRODUTOS WHERE [SABOR] = 'Maracujá'

UPDATE [PRODUTOS] SET [PREÇO LISTA] = [PREÇO LISTA] * 1.10
WHERE [SABOR] = 'Maracujá'

SELECT * FROM PRODUTOS WHERE [SABOR] = 'Maracujá'

-- Modifique o endereço do cliente 19290992743 para R. Jorge Emilio 23, em Santo Amaro, São Paulo, SP, CEP 8833223.

SELECT * FROM CLIENTES WHERE CPF = '19290992743'

UPDATE [CLIENTES] SET ENDEREÇO = 'R. Jorge Emilio 23', BAIRRO = 'Santo Amaro', CIDADE = 'São Paulo', ESTADO = 'SP', CEP = '8833223'
WHERE CPF = '19290992743'

-- Altere o volume de compra em 20% dos clientes do estado do Rio de Janeiro.

SELECT * FROM CLIENTES WHERE ESTADO = 'RJ'

UPDATE CLIENTES SET [VOLUME DE COMPRA] = [VOLUME DE COMPRA] * 1.20 
WHERE ESTADO = 'RJ'

