
	 SELECT * from [PRODUTOS] WHERE SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

	 DELETE FROM [PRODUTOS] WHERE [CÓDIGO] = '1001000'

	 SELECT * FROM [PRODUTOS]  WHERE [TAMANHO] = '1 Litro' AND SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

	 DELETE FROM [PRODUTOS] WHERE [TAMANHO] = '1 Litro' AND SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

	 SELECT [CODIGO DO PRODUTO] FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]

	 SELECT * FROM [PRODUTOS] WHERE [CÓDIGO] NOT IN (SELECT [CODIGO DO PRODUTO] FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS])

	 DELETE FROM [PRODUTOS] WHERE [CÓDIGO] NOT IN (SELECT [CODIGO DO PRODUTO] FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS])

-- NOT IN significa 'NÃO CONTIDO', ou seja, a linha acima pega os codigos que estão na tabela de produtos, mas não estão na tabela fonte

-- Exclua as notas fiscais (apenas o cabeçalho) cujos clientes tenham menos que 18 anos.

SELECT * FROM NOTAS

SELECT * FROM CLIENTES

SELECT *  FROM clientes WHERE idade < 18;

SELECT * FROM NOTAS WHERE CPF = '95939180787'

INSERT INTO NOTAS VALUES ('900','2015-01-01','95939180787','237',0.1)

SELECT A.NÚMERO FROM 
[NOTAS] A INNER JOIN [CLIENTES] B ON A.[CPF] = B.[CPF] 
WHERE B.[IDADE] < 18

DELETE A FROM [NOTAS] A
INNER JOIN [CLIENTES] B ON A.[CPF] = B.[CPF] 
WHERE B.[IDADE] < 18