
CREATE TABLE [PRODUTOS]
([CÓDIGO] VARCHAR(10) NOT NULL,
[DESCRITOR] VARCHAR(100) NULL,
[SABOR] VARCHAR(50) NULL,
[TAMANHO] VARCHAR(50) NULL,
[EMBALAGEM] VARCHAR(50) NULL,
[PREÇO LISTA] FLOAT NULL,
CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED ([CÓDIGO]))

CREATE TABLE [VENDEDORES]
([MATRÍCULA] VARCHAR(5) NOT NULL,
[NOME] VARCHAR(100) NULL,
[BAIRRO] VARCHAR(50) NULL,
[COMISSÃO] FLOAT NULL,
[DATA ADMISSÃO] DATE NULL,
[FÉRIAS] BIT NULL,
CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED ([MATRÍCULA]))