USE [VENDAS SUCOS]
GO

/****** Object:  Table [dbo].[NOTAS]    Script Date: 12/01/2021 15:50:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NOTAS](
	[NÚMERO] [varchar](5) NOT NULL,
	[DATA] [date] NULL,
	[CPF] [varchar](11) NULL,
	[MATRÍCULA] [varchar](5) NULL,
	[IMPOSTO] [float] NULL,
 CONSTRAINT [PK_NOTAS] PRIMARY KEY CLUSTERED 
(
	[NÚMERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


