CREATE TABLE [CLIENTE]
([CPF] VARCHAR (11) NOT NULL, -- chave primaria nunca pode aceitar nulos
[NOME] VARCHAR(100) NULL,
[ENDEREÇO] VARCHAR (150) NULL,
[BAIRRO] VARCHAR (50) NULL,
[CIDADE] VARCHAR (50) NULL, 
[ESTADO] VARCHAR (50) NOT NULL, 
[CEP] VARCHAR (8) NULL,
[DATA DE NASCIMENTO] DATE  NULL,
[IDADE] INT NULL,
[SEXO] VARCHAR(1),
[LIMITE CRÉDITO] FLOAT,
[VOLUME COMPRA] FLOAT,
[PRIMEIRA COMPRA] BIT,
CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED ([CPF]))






