
USE [VENDAS SUCOS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ITENS VENDIDOS](
    [NÚMERO] VARCHAR(5) NOT NULL,
    [CÓDIGO] VARCHAR(10) NOT NULL,
    [QUANTIDADE] INT NULL,
    [PREÇO] FLOAT NULL, 
CONSTRAINT [PK_ITENS_VENDIDOS] PRIMARY KEY CLUSTERED (
    [NÚMERO] ASC, [CÓDIGO] ASC -- isso aqui deixa numero e codigo como chaves primarias juntas (chave primaria composta)
) WITH (
    PAD_INDEX = OFF, 
    STATISTICS_NORECOMPUTE = OFF, 
    IGNORE_DUP_KEY = OFF, 
    ALLOW_ROW_LOCKS = ON, 
    ALLOW_PAGE_LOCKS = ON
) ON [PRIMARY]) ON [PRIMARY]
GO