
ALTER TABLE [dbo].[NOTAS]  WITH CHECK ADD  CONSTRAINT [FK_NOTAS_CLIENTES] FOREIGN KEY([CPF])
REFERENCES [dbo].[CLIENTES] ([CPF])

ALTER TABLE [dbo].[NOTAS]  WITH CHECK ADD  CONSTRAINT [FK_NOTAS_VENDEDORES] FOREIGN KEY([MATRICULA])
REFERENCES [dbo].[VENDEDORES] ([MATRÍCULA])

ALTER TABLE [dbo].[ITENS VENDIDOS]  WITH CHECK ADD  CONSTRAINT [FK_ITENS VENDIDOS_NOTAS] FOREIGN KEY([NÚMERO])
REFERENCES [dbo].[NOTAS] ([NÚMERO])

ALTER TABLE [dbo].[ITENS VENDIDOS]  WITH CHECK ADD  CONSTRAINT [FK_ITENS VENDIDOS_PRODUTOS] FOREIGN KEY([CÓDIGO])
REFERENCES [dbo].[PRODUTOS] ([CÓDIGO])
GO

