SELECT * FROM [TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
	CASE 
		WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END
FROM 
[TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
	CASE 
		WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END,
AVG([PREÇO DE LISTA])
FROM 
[TABELA DE PRODUTOS]
GROUP BY [NOME DO PRODUTO],
	CASE 
		WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END

SELECT YEAR(DATA), COUNT(*) FROM [NOTAS FISCAIS] GROUP BY YEAR(DATA)

-- Veja o ano de nascimento dos clientes e classifique-os como: 
-- nascidos antes de 1990 são adultos, 
-- nascidos entre 1990 e 1995 são jovens 
-- e nascidos depois de 1995 são crianças. 
-- Liste o nome do cliente e esta classificação.

SELECT NOME, 
	CASE 
		WHEN YEAR([DATA DE NASCIMENTO]) < 1990 THEN 'ADULTO'
		WHEN YEAR([DATA DE NASCIMENTO]) <= 1995 THEN 'JOVEM'
		ELSE 'CRIANÇA'
	END as [Classificação Etária]
FROM [TABELA DE CLIENTES]


