-- Temos o CAST e o CONVERT

-- CAST é universal para os sql's

-- CONVERT é especifico do SQL SERVER

SELECT CONVERT(VARCHAR, GETDATE(), 101)

SELECT CONVERT(VARCHAR, GETDATE(), 113)

SELECT CONVERT(VARCHAR, GETDATE(), 130)

SELECT CONVERT(decimal(10,5), 193.57)

SELECT * FROM [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  [PREÇO DE LISTA] 
from [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  CONVERT(VARCHAR, [PREÇO DE LISTA]) 
from [TABELA DE PRODUTOS]

-- Queremos construir um SQL cujo resultado seja, para cada cliente: 
-- **"O cliente João da Silva faturou 120000 no ano de 2016".
-- Somente para o ano de 2016.

SELECT * FROM [TABELA DE CLIENTES]

SELECT NOME, NF.CPF, NF.NUMERO FROM 
[TABELA DE CLIENTES] TC INNER JOIN [NOTAS FISCAIS] NF 
ON TC.CPF = NF.CPF

SELECT * FROM 
(SELECT NOME, NF.CPF, NF.NUMERO, NF.DATA FROM 
[TABELA DE CLIENTES] TC INNER JOIN [NOTAS FISCAIS] NF 
ON TC.CPF = NF.CPF) X INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON X.NUMERO = INF.NUMERO

SELECT NOME, QUANTIDADE, PREÇO, DATA FROM 
(SELECT NOME, NF.CPF, NF.NUMERO, NF.DATA FROM 
[TABELA DE CLIENTES] TC INNER JOIN [NOTAS FISCAIS] NF 
ON TC.CPF = NF.CPF) X INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON X.NUMERO = INF.NUMERO

SELECT NOME, DATA, SUM(QUANTIDADE * PREÇO) AS FATURAMENTO FROM 
(SELECT NOME, NF.CPF, NF.NUMERO, NF.DATA FROM 
[TABELA DE CLIENTES] TC INNER JOIN [NOTAS FISCAIS] NF 
ON TC.CPF = NF.CPF) X INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON X.NUMERO = INF.NUMERO
GROUP BY X.NUMERO, INF.NUMERO, NOME, DATA HAVING YEAR(DATA) = 2016

SELECT NOME, YEAR(DATA) AS DATA, SUM(QUANTIDADE * PREÇO) AS FATURAMENTO FROM 
(SELECT NOME, NF.CPF, NF.NUMERO, NF.DATA FROM 
[TABELA DE CLIENTES] TC INNER JOIN [NOTAS FISCAIS] NF 
ON TC.CPF = NF.CPF) X INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON X.NUMERO = INF.NUMERO
WHERE YEAR(DATA) = 2016
GROUP BY YEAR(DATA), X.NOME

SELECT 'O cliente ' +
		TAB.NOME + 
		' faturou ' +
		CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), TAB.FATURAMENTO))  +
		' no ano de 2016'
FROM 
(SELECT NOME, YEAR(DATA) AS DATA, SUM(QUANTIDADE * PREÇO) AS FATURAMENTO FROM 
(SELECT NOME, NF.CPF, NF.NUMERO, NF.DATA FROM 
[TABELA DE CLIENTES] TC INNER JOIN [NOTAS FISCAIS] NF 
ON TC.CPF = NF.CPF) X INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON X.NUMERO = INF.NUMERO
WHERE YEAR(DATA) = 2016
GROUP BY YEAR(DATA), X.NOME) TAB

-- JEITO DO PROF:

SELECT CONCAT('O cliente ', TC.NOME, ' faturou ', 
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), SUM(INF.QUANTIDADE * INF.[PREÇO]))), ' no ano ',   CONVERT(VARCHAR, YEAR(NF.DATA))) AS SENTENCA FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE CLIENTES] TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA) = 2016
GROUP BY TC.NOME, YEAR(DATA)


