
SELECT 2

SELECT LTRIM('      OLA')

SELECT RTRIM('OLA      ')

SELECT CONCAT('OLA ','TUDO BEM')

SELECT 'OLA ' + 'TUDO BEM'

SELECT LEFT('RUA AUGUSTA',3) 

SELECT RIGHT('RUA AUGUSTA',7) 

SELECT UPPER('rua augusta')   

SELECT LOWER('RUA AUGUSTA')   

SELECT REPLACE('R. AUGUSTA','R.','RUA') 

SELECT SUBSTRING('RUA AUGUSTA', 1, 3) 

SELECT SUBSTRING('RUA AUGUSTA', 2, 4) 

SELECT LEN('RUA AUGUSTA')  

SELECT * FROM [TABELA DE CLIENTES]

SELECT CONCAT(NOME, ' (', CPF, ') ') FROM [TABELA DE CLIENTES]

-- Faça uma consulta que lista o nome do cliente e o endereço completo (com rua, bairro, cidade e estado).

SELECT CONCAT(
	'NOME: ', NOME,
	', ENDEREÇO: ', [ENDERECO 1],
	' ', [BAIRRO],
	' ', [CIDADE],
	' ', [ESTADO]) FROM [TABELA DE CLIENTES]









