SELECT * FROM [TABELA DE PRODUTOS]

SELECT INF.[CODIGO DO PRODUTO], YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO FROM 
[ITENS NOTAS FISCAIS] INF INNER JOIN [NOTAS FISCAIS] NF 
ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY INF.[CODIGO DO PRODUTO], YEAR(NF.DATA)

SELECT TP.SABOR, AUX1.ANO, AUX1.FATURAMENTO FROM (
SELECT INF.[CODIGO DO PRODUTO], YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO FROM 
[ITENS NOTAS FISCAIS] INF INNER JOIN [NOTAS FISCAIS] NF 
ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY INF.[CODIGO DO PRODUTO], YEAR(NF.DATA)) AUX1 INNER JOIN [TABELA DE PRODUTOS] TP
ON AUX1.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO] 

SELECT TP.SABOR, AUX1.ANO, SUM(AUX1.FATURAMENTO) AS FATURAMENTO FROM (
SELECT INF.[CODIGO DO PRODUTO], YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO FROM 
[ITENS NOTAS FISCAIS] INF INNER JOIN [NOTAS FISCAIS] NF 
ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY INF.[CODIGO DO PRODUTO], YEAR(NF.DATA)) AUX1 INNER JOIN [TABELA DE PRODUTOS] TP
ON AUX1.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
GROUP BY TP.SABOR, AUX1.ANO

SELECT AUX1.ANO, SUM(AUX1.FATURAMENTO) AS FATURAMENTO FROM (
SELECT INF.[CODIGO DO PRODUTO], YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO FROM 
[ITENS NOTAS FISCAIS] INF INNER JOIN [NOTAS FISCAIS] NF 
ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY INF.[CODIGO DO PRODUTO], YEAR(NF.DATA)) AUX1 INNER JOIN [TABELA DE PRODUTOS] TP
ON AUX1.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
GROUP BY AUX1.ANO


SELECT TAB1.SABOR, TAB1.ANO, CONVERT(DECIMAL(15,2), TAB1.FATURAMENTO) AS FATURAMENTO, CONVERT(VARCHAR, CONVERT( DECIMAL(15,4), SUM((TAB1.FATURAMENTO/TAB2.FATURAMENTO) * 100))) + ' %' AS PARTICIPACAO  
FROM 
	(SELECT TP.SABOR, AUX1.ANO, SUM(AUX1.FATURAMENTO) AS FATURAMENTO FROM (
	SELECT INF.[CODIGO DO PRODUTO], YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO FROM 
	[ITENS NOTAS FISCAIS] INF INNER JOIN [NOTAS FISCAIS] NF 
	ON INF.NUMERO = NF.NUMERO
	WHERE YEAR(NF.DATA) = 2016
	GROUP BY INF.[CODIGO DO PRODUTO], YEAR(NF.DATA)) AUX1 INNER JOIN [TABELA DE PRODUTOS] TP
	ON AUX1.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	GROUP BY TP.SABOR, AUX1.ANO) TAB1 
INNER JOIN 
	(SELECT AUX1.ANO, SUM(AUX1.FATURAMENTO) AS FATURAMENTO FROM (
	SELECT INF.[CODIGO DO PRODUTO], YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO FROM 
	[ITENS NOTAS FISCAIS] INF INNER JOIN [NOTAS FISCAIS] NF 
	ON INF.NUMERO = NF.NUMERO
	WHERE YEAR(NF.DATA) = 2016
	GROUP BY INF.[CODIGO DO PRODUTO], YEAR(NF.DATA)) AUX1 INNER JOIN [TABELA DE PRODUTOS] TP
	ON AUX1.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	GROUP BY AUX1.ANO) TAB2
ON TAB1.ANO = TAB2.ANO
GROUP BY TAB1.SABOR, TAB1.ANO, TAB1.FATURAMENTO
ORDER BY FATURAMENTO DESC

-------------------------------------------------------------------------------------------

SELECT AUX1.TAMANHO, AUX1.ANO, CONVERT(DECIMAL(15,2), AUX1.FATURAMENTO) AS FATURAMENTO, 
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2),(AUX1.FATURAMENTO/AUX2.TOTAL) * 100)) + ' %' 
AS PERCENTUAL FROM
(SELECT TP.TAMANHO, YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY TP.TAMANHO, YEAR(NF.DATA)) AUX1
INNER JOIN (SELECT YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS TOTAL
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY YEAR(NF.DATA)) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC


