SELECT TOP (1000) [CPF]
      ,[NOME]
      ,[ENDERECO 1]
      ,[ENDERECO 2]
      ,[BAIRRO]
      ,[CIDADE]
      ,[ESTADO]
      ,[CEP]
      ,[DATA DE NASCIMENTO]
      ,[IDADE]
      ,[SEXO]
      ,[LIMITE DE CREDITO]
      ,[VOLUME DE COMPRA]
      ,[PRIMEIRA COMPRA]
  FROM [SUCOS_VENDAS].[dbo].[TABELA DE CLIENTES]

  SELECT [CPF]
      ,[NOME]
      ,[ENDERECO 1]
      ,[ENDERECO 2]
      ,[BAIRRO]
      ,[CIDADE]
      ,[ESTADO]
      ,[CEP]
      ,[DATA DE NASCIMENTO]
      ,[IDADE]
      ,[SEXO]
      ,[LIMITE DE CREDITO]
      ,[VOLUME DE COMPRA]
      ,[PRIMEIRA COMPRA]
  FROM [TABELA DE CLIENTES]

  SELECT * FROM [TABELA DE CLIENTES]

  SELECT [CPF]
      ,[NOME]
  FROM [TABELA DE CLIENTES]

  SELECT [CPF] AS IDENTIFCADOR -- "alias”, um nome fantasia para o nome da coluna
      ,[NOME] AS CLIENTE
  FROM [TABELA DE CLIENTES]

    SELECT [NOME] AS CLIENTE,
	[CPF] AS IDENTIFCADOR
  FROM [TABELA DE CLIENTES]

  SELECT [NOME], [MATRICULA] FROM [TABELA DE VENDEDORES]

  SELECT * FROM [TABELA DE VENDEDORES] WHERE [NOME] = 'Cláudia Morais' 

  SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] = 4.555

  SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] > 10

  SELECT * FROM [TABELA DE PRODUTOS]  WHERE [PREÇO DE LISTA] < 10 ORDER BY [PREÇO DE LISTA] ASC 

  SELECT * FROM [TABELA DE PRODUTOS]  WHERE [PREÇO DE LISTA] < 10 ORDER BY [PREÇO DE LISTA] DESC 

  SELECT * FROM [TABELA DE PRODUTOS]  WHERE [PREÇO DE LISTA] >= 5 AND [PREÇO DE LISTA] <= 10 ORDER BY [PREÇO DE LISTA] DESC

  SELECT * FROM [TABELA DE PRODUTOS] WHERE [EMBALAGEM] > 'Lata'

  SELECT * FROM [TABELA DE PRODUTOS] WHERE [EMBALAGEM] <> 'Lata' -- <> é o diferente

  SELECT * FROM [TABELA DE VENDEDORES] WHERE [PERCENTUAL COMISSÃO] > 0.10

  SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-09-11'

  SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] > '1995-09-11'

  SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] < '1995-09-11'

  SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995

  SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) < 1995

  SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) > 1995

  SELECT * FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = 09

  SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = 20

  SELECT * FROM [TABELA DE VENDEDORES] WHERE YEAR([DATA ADMISSÃO]) >= 2016



